service: wmra-rss

frameworkVersion: ">=2.24.0"

provider:
  name: aws
  runtime: nodejs16.x

functions:
  check:
    handler: index.check
    description: generate RSS feed from www.wmra.info web-site
    events:
      - http:
          path: rss
          method: get
          cors: true
          integration: lambda
          response:
            headers:
              Content-Type: "'text/xml'"
            template: $input.path('$')
